# Generated by Django 3.2 on 2021-05-17 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybylink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paybylink',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paybylink',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
