# Generated by Django 3.2 on 2021-05-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0002_auto_20210517_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybylink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
