# Generated by Django 3.2 on 2021-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0003_alter_paybylink_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(max_length=30)),
                ('cardholder_name', models.CharField(max_length=20)),
                ('cardholder_surname', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(max_length=30)),
                ('iban', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='paybylink',
            options={'ordering': ['created_at']},
        ),
    ]
