# Generated by Django 3.2 on 2021-05-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0005_auto_20210521_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybylink',
            name='customer_id',
            field=models.IntegerField(blank='True', default=2),
            preserve_default=False,
        ),
    ]
