# Generated by Django 3.2 on 2021-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0006_paybylink_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybylink',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='EUR', max_length=5),
        ),
    ]
