# Generated by Django 3.2 on 2021-05-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0007_alter_paybylink_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank='True')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('PLN', 'PLN')], default='EUR', max_length=5)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(max_length=30)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='paybylink',
            options={},
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paybylink',
            name='id',
        ),
        migrations.AddField(
            model_name='paybylink',
            name='paymentmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.paymentmodel'),
            preserve_default=False,
        ),
    ]
