# Generated by Django 3.2 on 2021-05-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0008_auto_20210522_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelOptions(
            name='directpayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='card',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.RemoveField(
            model_name='directpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='directpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='directpayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='directpayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='directpayment',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='paymentmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.paymentmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directpayment',
            name='paymentmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.paymentmodel'),
            preserve_default=False,
        ),
    ]
