# Generated by Django 3.2 on 2021-05-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0009_auto_20210522_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={},
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_type',
            field=models.CharField(choices=[('pbl', 'Pay_by_link'), ('dp', 'DirectPayment'), ('card', 'Card')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
