# Generated by Django 3.2 on 2021-05-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0011_auto_20210523_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='payment_type',
        ),
    ]
