# Generated by Django 3.2 on 2021-05-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0012_remove_paymentmodel_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_ID',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.card')),
                ('customer_id', models.PositiveIntegerField(blank='True')),
            ],
            bases=('transaction_reports.card',),
        ),
        migrations.CreateModel(
            name='DP_ID',
            fields=[
                ('directpayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.directpayment')),
                ('customer_id', models.PositiveIntegerField(blank='True')),
            ],
            bases=('transaction_reports.directpayment',),
        ),
        migrations.CreateModel(
            name='PBL_ID',
            fields=[
                ('paybylink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.paybylink')),
                ('customer_id', models.PositiveIntegerField(blank='True')),
            ],
            bases=('transaction_reports.paybylink',),
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='customer_id',
        ),
    ]
