# Generated by Django 3.2.3 on 2021-07-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_reports', '0013_auto_20210523_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PblID',
            fields=[
                ('paybylink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.paybylink')),
                ('customer_id', models.PositiveIntegerField(blank='True', unique=True)),
            ],
            bases=('transaction_reports.paybylink',),
        ),
        migrations.RenameModel(
            old_name='Card_ID',
            new_name='CardID',
        ),
        migrations.RenameModel(
            old_name='PBL_ID',
            new_name='DpID',
        ),
        migrations.RemoveField(
            model_name='dpid',
            name='paybylink_ptr',
        ),
        migrations.AddField(
            model_name='dpid',
            name='directpayment_ptr',
            field=models.OneToOneField(auto_created=True, default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_reports.directpayment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DP_ID',
        ),
    ]
